### ISSUE TITLE
Nesting messages - Show useful error message

### ISSUE THREAD

**Issue by radiorambo** [opral/inlang-paraglide-js#159]
Here in [docs](https://inlang.com/m/gerre34r/library-inlang-paraglideJs/usage#working-with-the-inlang-message-format
) it says it isn't supported, but here in an [example](https://github.com/opral/example/blob/main/resources/en.json
), it is using nested messages.

But when I tried to use that example messages, then I got this error `An error occured in loadMessages() caused by TypeError: u.slice is not a function`, which took me some time to figure out that nesting messages isn't supported and error disappeared as soon as I removed the nesting messages from the example I copied. 

So proper error message like `nesting messages isn't supported and we don't plan to support in future too, due to some limitations. For more details, refer this url` would be great

**Comment by LorisSigrist** [comment]
Thanks for reporting this. I updated the example to reflect what's currently recommended. 

We will add a better error-message

**Comment by artolshansky** [comment]
Do you have any plans to add support for nested messages?

**Comment by samuelstroschein** [comment]
@artolshansky no. nesting messages breaks tree shaking. you can "nest" messages with an underscore like so `login_button`

**Comment by Secreto31126** [comment]
@samuelstroschein I would like to bump this issue, since v2 now does allow having objects for message variants. When I upgraded from v1 to v2, I accidentally forgot to update this mini string in the proyect.inlang/settings.json:

```diff
"plugin.inlang.messageFormat": {
-	"pathPattern": "./messages/{languageTag}.json"
+ 	"pathPattern": "./messages/{locale}.json"
},
```

Which resulted in a nasty nasty 3kb error log, and the only readable text was `u.slice is not a function`.

Now more than ever would be nice to improve this message error, as it will be way more common to use objects instead of strings, and some people would have real headaches discovering why they failed in the legacy mode (`loadLegacyMessages`). Maybe a link saying the feature is only supported in v2 and how to propperly update to it.

A warning saying `You are in legacy mode because 'x reason'` would also be really cool, I found my mini diff by mere chance.

**Comment by samuelstroschein** [comment]
If anyone wants to make a PR, I'll quickly review and merge it. 

Here is the source code responsible for importing messages that should throw if a message uses nesting https://github.com/opral/monorepo/blob/main/inlang/packages/plugins/inlang-message-format/src/import-export/importFiles.ts

**Comment by Secreto31126** [comment]
I just updated to plugin-message-format@3 in the settings file, and now it seems it works with both `languageTag` and `locale`. Ngl, I'm super confused now 😆

I feel the modules system is quite unusual, specially since there's no way to know when a new version is available/required.

**Comment by Secreto31126** [comment]
Ok, I just went through the code, and I feel like it definitely was a me problem with the version missmatch in ParaglideJS and the message-format plugin, my bad!

Although, if you are still interested, I think a try-catch in the loadLegacyMessages function within loadProjectFromDirectory.js would be more interesting, as it could log a message saying the input wasn't the expected one, no matter which version of the plugin you are using, and propose the user to update to a newer version.

What do you think?

**Comment by samuelstroschein** [comment]
> I just updated to plugin-message-format@3 in the settings file, and now it seems it works with both languageTag and locale. Ngl, I'm super confused now 😆

That's why, historically, we recommended using `@latest` as version for the plugins. We have no update mechanism in place yet. One step at a time :D 

>  I think a try-catch in the loadLegacyMessages function within loadProjectFromDirectory.js would be more interesting, as it could log a message saying the input wasn't the expected one

Not worth it. 

We expect the legacy `loadMessages` API to be phased out quite quickly. We are only waiting for the Paraglide 2.0 and Sherlock v2 release which are both expected to happen next week.

**Comment by Secreto31126** [comment]
Ok, I will start using `@latest` for the plugins, thanks for the tip.

You might want to talk with the team behind the Svelte CLI (sv), because the default right now is to pin the versions:
https://github.com/sveltejs/cli/blob/e325bb2c71fe3fefce4cfcb07e3ab33870eddb45/packages/addons/paraglide/index.ts#L17-L31

The idea of SQLite within git scares me 🤣.

Looking foward to the final v2 release! And sorry for the chaos :]

**Comment by samuelstroschein** [comment]
I will update the sv CLi to point to v3. Thanks for the heads up!

**Comment by samuelstroschein** [comment]
Nesting is now supported in the paraglide js 2.0 beta https://github.com/opral/inlang-paraglide-js/issues/201#issuecomment-2680006131
